  - {name: if.StatsDuplexStatus, oid: .1.3.6.1.2.1.10.7.2.1.19, access: read , values: {1: Down, 2: Full, 3: Half}}
  - {name: sensors.temperature.cpu, oid: .1.3.6.1.4.1.8886.1.1.4.2.1}


    # DHCP Snooping (can be wrong):
  - {name: dhcpSnooping.bindMac, oid: .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.2} # .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.2.4.10.31.10.7 = Hex-STRING: 90 1B 0E 65 51 36  |  Do not know what is '4' before ip addresses
  - {name: dhcpSnooping.bindLease, oid: .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.3} # .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.3.4.10.31.10.7 = Gauge32: 540  |  remaining lease time in seconds   |  Do not know what is '4' before ip addresses
  - {name: dhcpSnooping.bindVlan, oid: .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.4} # .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.4.4.10.31.10.7 = INTEGER: 31  |  Do not know what is '4' before ip addresses
  - {name: dhcpSnooping.bindPort, oid: .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.5} # .1.3.6.1.4.1.8886.6.1.23.1.1.5.1.5.4.10.31.10.7 = INTEGER: 2082476041   |    Do not know what is '4' before ip addresses