# Аналог LACP
- { name: port.loadShare.status, oid: .1.3.6.1.4.1.1916.1.4.3.1.4, values: {
    1: 'active(1)',
    2: 'notInService(2)',
    3: 'notReady(3)',
    4: 'createAndGo(4)',
    5: 'createAndWait(5)',
    6: 'destroy(6)'
  }
}

- {name: sensors.temperature.cpu, oid: .1.3.6.1.4.1.1916.1.1.1.8.0 }

- {name: extreme.fdbMacExosFdbMacAddress, oid: .1.3.6.1.4.1.1916.1.16.4.1.1} #.1.3.6.1.4.1.1916.1.16.4.1.1.4.141.56.32.98.186.1000006 = Hex-STRING: 04 8D 38 20 62 BA
- {name: extreme.fdbMacExosFdbVlanIfIndex , oid: .1.3.6.1.4.1.1916.1.16.4.1.2} #.1.3.6.1.4.1.1916.1.16.4.1.2.4.141.56.32.98.186.1000006 = INTEGER: 1000006
- {name: extreme.fdbMacExosFdbPortIfIndex , oid: .1.3.6.1.4.1.1916.1.16.4.1.3} #.1.3.6.1.4.1.1916.1.16.4.1.3.4.141.56.32.98.186.1000006 = INTEGER: 1026
- {name: extreme.fdbMacExosFdbStatus, oid: .1.3.6.1.4.1.1916.1.16.4.1.4, values: {1: OTHER, 2: INVALID, 3: LEARNED, 4: SELF, 5: MGMT}} #.1.3.6.1.4.1.1916.1.16.4.1.4.4.141.56.32.98.186.1000006 = INTEGER: 3
- {name: extreme.vlanIfVlanId, oid: .1.3.6.1.4.1.1916.1.2.1.2.1.10 } # .1.3.6.1.4.1.1916.1.2.1.2.1.10.1000004 = INTEGER: 1

- {name: extreme.vlanIfDescr, oid: .1.3.6.1.4.1.1916.1.2.1.2.1.2 } #vlan name (.1.3.6.1.4.1.1916.1.2.1.2.1.2.1000004 = STRING: "Default")
- {name: extreme.vlanOpaqueTaggedPorts, oid: .1.3.6.1.4.1.1916.1.2.6.1.1.1 } # .1.3.6.1.4.1.1916.1.2.6.1.1.1.1000005.1 = Hex-STRING: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
- {name: extreme.vlanOpaqueUntaggedPorts, oid: .1.3.6.1.4.1.1916.1.2.6.1.1.2 } # .1.3.6.1.4.1.1916.1.2.6.1.1.2.1000005.1 = Hex-STRING: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00