############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: Dlink DGS-1210-28/ME/A2
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-28-me-a2.yml
   detect: {description: ^DGS-1210-28\/ME\/A2$,  objid: ^.*171.10.76.28.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot

 - name: Dlink DGS-1210-20/ME/A1
   ports: 20
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-20-me-a1.yml
   detect: {description: ^DGS-1210-20\/ME\/A1$,  objid: ^.*171\.10\.76\.31\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot

 - name: Dlink DGS-1210-10/ME/A1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-10-me-a1.yml
   detect: {description: ^DGS-1210-10\/ME\/A1$,  objid: ^.*171.10.76.35.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot

 - name: Dlink DGS-1210-20/ME/B1
   ports: 20
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-20-me-b1.yml
   detect: {description: ^DGS-1210-20\/ME\/B1$,  objid: ^.*171.10.76.31.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot

 - name: Dlink DGS-1210-28/ME/B1
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-28-me-b1.yml
   detect: {description: ^DGS-1210-28\/ME\/B1$,  objid: ^.*171.10.76.28.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot

 - name: Dlink DGS-1210-28XS/ME/B1
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/dgs-1210-28xs-me-b1.yml
   detect: {description: ^DGS-1210-28XS\/ME\/B1$,  objid: ^.*171.10.76.39.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
