- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.1.1.2, values: {100: Cooper, 101: Fiber}}
- {name: dlink.PortInfoLinkStatus, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.1.1.4, values: {2: Up, 3: Down}}
- {name: dlink.PortInfoNwayStatus, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.1.1.5, values: {1: Down, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Half, 7: 1G-Full}}
- {name: dlink.PortCtrlPortAdminState, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.2.1.3, values: {3: Enabled, 2: Disabled}}
- {name: dlink.PortCtrlPortNwayState, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.2.1.4, values: {1: Auto, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Half, 7: 1G-Full}}
- {name: dlink.PortCtrlAddressLearning, oid: .1.3.6.1.4.1.171.11.113.1.2.2.2.2.1.7, values: {2: Disabled, 3: Enabled}}

- {name: ddm.power.tx, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.5}
- {name: ddm.power.rx, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.6}