- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.2.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.PortInfoLinkStatus, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.1.1.5, values: {2: Up, 3: Down}}
- {name: dlink.PortInfoNwayStatus, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.1.1.6, values: {0: Down, 2: Down, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full, 10: 1G-Full}}
- {name: dlink.PortCtrlPortAdminState, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.2.1.4, values: {3: Enabled, 2: Disabled}}
- {name: dlink.PortCtrlPortNwayState, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.2.1.5, values: {2: Auto, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full}}
- {name: dlink.PortCtrlAddressLearning, oid: .1.3.6.1.4.1.171.11.113.5.1.2.3.2.1.7, values: {2: Disabled, 3: Enabled}}

