- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.11.105.1.2.3.1.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.PortInfoLinkStatus, oid: .1.3.6.1.4.1.171.11.105.1.2.3.1.1.5, values: {2: Up, 3: Down}}
- {name: dlink.PortInfoNwayStatus, oid: .1.3.6.1.4.1.171.11.105.1.2.3.1.1.6, values: {0: Other, 1: Empty, 2: Down, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full}}
- {name: dlink.PortCtrlPortAdminState, oid: .1.3.6.1.4.1.171.11.105.1.2.3.2.1.4, values: {3: Enabled, 2: Disabled}}
- {name: dlink.PortCtrlPortNwayState, oid: .1.3.6.1.4.1.171.11.105.1.2.3.2.1.5, values: {0: Other, 1: Disabled, 2: Auto, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full}}

- {name: agent.PortUtilizationTx, oid: .1.3.6.1.4.1.171.12.1.1.7.1.2 }
- {name: agent.PortUtilizationRx, oid: .1.3.6.1.4.1.171.12.1.1.7.1.3 }
- {name: agent.PortUtilizationUtil, oid: .1.3.6.1.4.1.171.12.1.1.7.1.4 }

