
#Port diagnostic
- {name: dlink.CableDiagPortIndex, oid: .1.3.6.1.4.1.171.12.58.1.1.1.1}
- {name: dlink.CableDiagPortType, oid: .1.3.6.1.4.1.171.12.58.1.1.1.2, values: {0: FE, 1: GE, 2: Other}}
- {name: dlink.CableDiagLinkStatus, oid: .1.3.6.1.4.1.171.12.58.1.1.1.3, values: {0: Down, 1: Up, 2: Other}}
- {name: dlink.CableDiagPair1Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.5, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair2Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.6, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair3Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.4, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair4Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.7, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair1Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.9}
- {name: dlink.CableDiagPair2Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.10}
- {name: dlink.CableDiagPair3Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.8}
- {name: dlink.CableDiagPair4Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.11}
- {name: dlink.CableDiagAction, oid: .1.3.6.1.4.1.171.12.58.1.1.1.12, values: {1: Action, 2: Processing, 3: Other}}
- {name: dlink.CableDiagStatus, oid: .1.3.6.1.4.1.171.12.58.1.1.1.13, values: {1: NotRun, 2: Proccessing, 3: LastTestOk, 4: LastTestFailed}}


- {name: ddm.power.tx, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.5}
- {name: ddm.power.rx, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.6}
