- {name: dlink.PortInfoLinkStatus, oid: .1.3.6.1.4.1.171.11.63.3.2.2.1.1.4, values: {2: Up, 3: Down}}
- {name: dlink.PortInfoNwayStatus, oid: .1.3.6.1.4.1.171.11.63.3.2.2.1.1.5, values: {1: Down, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Half, 7: 1G-Full}}
- {name: dlink.PortCtrlPortAdminState, oid: .1.3.6.1.4.1.171.11.63.3.2.2.2.1.2, values: {3: Enabled, 2: Disabled}}
- {name: dlink.PortCtrlPortNwayState, oid: .1.3.6.1.4.1.171.11.63.3.2.2.2.1.3, values: {1: Auto, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Half, 7: 1G-Full}}

- {name: dlink.DevCtrlCleanAllStatisticCounter, oid: .1.3.6.1.4.1.171.11.63.6.2.1.2.12.0, values: {1: normal, 2: active}}
- {name: dlink.DevCtrlSystemReboot, oid: .1.3.6.1.4.1.171.11.63.6.2.1.2.1.0, values: {1: other, 2: reboot, 3: save-config-and-reboot, 4: reboot-and-load-factory-default-config}}


