- {name: dlink.sysPortCtrlMediumType, oid: .1.3.6.1.4.1.171.10.134.2.1.1.100.1.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.sysPortCtrlSpeed, oid: .1.3.6.1.4.1.171.10.134.2.1.1.100.1.1.3, values: {1: 1G-Full, 2: 100-Full, 3: 100-Half, 4: 10-Full, 5: 10-Half, 6: Auto, 7: Disabled}}
- {name: dlink.sysPortCtrlOperStatus, oid: .1.3.6.1.4.1.171.10.134.2.1.1.100.1.1.4, values: {1: Down, 2: 1G-Full, 3: 100-Full, 4: 100-Half, 5: 10-Full, 6: 10-Half, 7: 10G-Full}}


#Port diagnostic
- {name: dlink.cableDiagTriggerIndex, oid: .1.3.6.1.4.1.171.10.134.2.1.35.1.0}
#INTEGER  { ok ( 0 ) , open ( 1 ) , short ( 2 ) , notAvailable ( 5 ) }
- {name: dlink.cableDiagPair3TestResult, oid: .1.3.6.1.4.1.171.10.134.2.1.35.2.0, values: {0: OK, 1: Open, 2: Short, 5: NotAvaliable}}
- {name: dlink.cableDiagPair3FaultDistance, oid: .1.3.6.1.4.1.171.10.134.2.1.35.3.0}

- {name: dlink.cableDiagPair1TestResult, oid: .1.3.6.1.4.1.171.10.134.2.1.35.4.0, values: {0: OK, 1: Open, 2: Short, 5: NotAvaliable}}
- {name: dlink.cableDiagPair1FaultDistance, oid: .1.3.6.1.4.1.171.10.134.2.1.35.5.0}

- {name: dlink.cableDiagPair2TestResult, oid: .1.3.6.1.4.1.171.10.134.2.1.35.6.0, values: {0: OK, 1: Open, 2: Short, 5: NotAvaliable}}
- {name: dlink.cableDiagPair2FaultDistance, oid: .1.3.6.1.4.1.171.10.134.2.1.35.7.0}

- {name: dlink.cableDiagPair4TestResult, oid: .1.3.6.1.4.1.171.10.134.2.1.35.8.0, values: {0: OK, 1: Open, 2: Short, 5: NotAvaliable}}
- {name: dlink.cableDiagPair4FaultDistance, oid: .1.3.6.1.4.1.171.10.134.2.1.35.9.0}
#INTEGER  { less50 ( 1 ) , from50to80 ( 2 ) , from80to100 ( 3 ) , from100to140 ( 4 ) , notAvailable ( 5 ) }
- {name: dlink.cableDiagLengthinRange, oid: .1.3.6.1.4.1.171.10.134.2.1.35.10.0, values: {1: '0-50', 2: '50-80', 3: '80-100', 4: '100-140', 5: NotAvaliable }}

