- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.10.76.39.1.1.13.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.sysPortCtrlSpeed, oid: .1.3.6.1.4.1.171.10.76.39.1.1.13.1.3, values: {1: 1G-Full, 2: 100-Full, 3: 100-Half, 4: 10-Full, 5: 10-Half, 6: Auto}}
- {name: dlink.sysPortCtrlOperStatus, oid: .1.3.6.1.4.1.171.10.76.39.1.1.13.1.4, values: {1: Down, 2: 1G-Full, 3: 100-Full, 4: 100-Half, 5: 10-Full, 6: 10-Half, 7: 10G-Full}}
- {name: dlink.sysPortCtrlState, oid: .1.3.6.1.4.1.171.10.76.39.1.1.13.1.11, values: {1: Enabled, 2: Disabled}}
- {name: dlink.sysPortLinkChangeTime, oid: .1.3.6.1.4.1.171.10.76.39.1.1.14.1.5}
- {name: dlink.sysPortCtrlType, oid: .1.3.6.1.4.1.171.10.76.39.1.1.13.1.8, values: {1: FE, 2: GE, 3: SFP-100, 4: SFP-1G, 5: SFP-10G}}


#Port diagnostic
- {name: dlink.CableDiagPortIndex, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.1}
- {name: dlink.CableDiagPortType, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.2, values: {0: FE, 1: GE, 2: Other}}
- {name: dlink.CableDiagLinkStatus, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.3, values: {0: Down, 1: Up, 2: Other}}
#INTEGER  { ok ( 0 ) , open ( 1 ) , short ( 2 ) , open-short ( 3 ) , crosstalk ( 4 ) , mismatch ( 5 ) , linedriver ( 6 ) , unknown ( 7 ) , count ( 8 ) , no-cable ( 9 ) , other ( 10 ) }
- {name: dlink.CableDiagPair3Status, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.4, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair1Status, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.5, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair2Status, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.6, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair4Status, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.7, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair3Length, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.8}
- {name: dlink.CableDiagPair1Length, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.9}
- {name: dlink.CableDiagPair2Length, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.10}
- {name: dlink.CableDiagPair4Length, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.11}
- {name: dlink.CableDiagAction, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.12, values: {1: Action, 2: Processing, 3: Other, 4: ActionCarefulMode}}
- {name: dlink.CableDiagStatus, oid: .1.3.6.1.4.1.171.10.76.39.1.35.1.1.13, values: {1: NotRun, 2: Proccessing, 3: LastTestOk, 4: LastTestFailed}}
